typstc cmd file fmt:
  typst {{cmd}} --root=. --font-path=fonts src/{{file}}.typ build/{{file}}.{{fmt}}

build: (typstc "compile" "main" "pdf")
watch: (typstc "watch" "main" "pdf")

trunc:
  pdftk build/main.pdf cat 2 8 18 output build/garbage.pdf
  pdftk build/main.pdf cat 1 3-7 9-17 19-end output build/trunc.pdf
